### ISSUE TITLE
关于载入的数据集?

### ISSUE THREAD

**Issue by Jhy1993** [echo740/DANSER-WWW-19#6]
载入的文件中有很多list, 有一些我自行理解,有一些不是很理解.   
 u_friend_list = pickle.load(f) # U-U 代表friend关系 长度为num_user的list, 每个元素也是一个list,代表其朋友
    u_read_list = pickle.load(f) # U-I 代表点击关系
    uf_read_list = pickle.load(f) # U-U-I, list中每个元素是 friend点击过的item
    下面的几个文件代表什么含义呢?
    i_friend_list = pickle.load(f) 
    i_read_list = pickle.load(f)
    if_read_list = pickle.load(f)
    i_link_list = pickle.load(f)

**Comment by echo740** [comment]
i_friend_list，i_read_list，if_read_list和u_friend_list，u_read_list, uf_read_list是对应关系，前三个是和item的相关，后三个是和user相关的。前三个分别指item相关的item，点击过item的用户，点击过item相关的item的用户。
最后一个i_link_list是item与相关item的相似系数
